# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M:\Z\pkpm_CircleGGZ_section_check\main_ui.ui'
#
# Created: Sun Jun  9 16:33:10 2013
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pkpm(object):
    def setupUi(self, pkpm):
        pkpm.setObjectName(_fromUtf8("pkpm"))
        pkpm.resize(651, 365)
        self.centralWidget = QtGui.QWidget(pkpm)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pb_open = QtGui.QPushButton(self.centralWidget)
        self.pb_open.setGeometry(QtCore.QRect(20, 330, 81, 23))
        self.pb_open.setObjectName(_fromUtf8("pb_open"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 311))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 71, 281))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 20, 161, 282))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.le_nc = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_nc.setObjectName(_fromUtf8("le_nc"))
        self.verticalLayout_4.addWidget(self.le_nc)
        self.le_b = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_b.setObjectName(_fromUtf8("le_b"))
        self.verticalLayout_4.addWidget(self.le_b)
        self.le_t = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_t.setObjectName(_fromUtf8("le_t"))
        self.verticalLayout_4.addWidget(self.le_t)
        self.le_cx = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_cx.setObjectName(_fromUtf8("le_cx"))
        self.verticalLayout_4.addWidget(self.le_cx)
        self.le_cy = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_cy.setObjectName(_fromUtf8("le_cy"))
        self.verticalLayout_4.addWidget(self.le_cy)
        self.le_lc = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_lc.setObjectName(_fromUtf8("le_lc"))
        self.verticalLayout_4.addWidget(self.le_lc)
        self.le_nfc = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_nfc.setObjectName(_fromUtf8("le_nfc"))
        self.verticalLayout_4.addWidget(self.le_nfc)
        self.le_rcc = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_rcc.setObjectName(_fromUtf8("le_rcc"))
        self.verticalLayout_4.addWidget(self.le_rcc)
        self.le_rsc = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_rsc.setObjectName(_fromUtf8("le_rsc"))
        self.verticalLayout_4.addWidget(self.le_rsc)
        self.le_m = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_m.setObjectName(_fromUtf8("le_m"))
        self.verticalLayout_4.addWidget(self.le_m)
        self.le_n = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.le_n.setObjectName(_fromUtf8("le_n"))
        self.verticalLayout_4.addWidget(self.le_n)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 341, 311))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 151, 281))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_2.addWidget(self.label_22)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(170, 20, 161, 282))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.le_ac = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_ac.setObjectName(_fromUtf8("le_ac"))
        self.verticalLayout_5.addWidget(self.le_ac)
        self.le_as = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_as.setObjectName(_fromUtf8("le_as"))
        self.verticalLayout_5.addWidget(self.le_as)
        self.le_theta = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_theta.setObjectName(_fromUtf8("le_theta"))
        self.verticalLayout_5.addWidget(self.le_theta)
        self.le_maxtheta = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_maxtheta.setObjectName(_fromUtf8("le_maxtheta"))
        self.verticalLayout_5.addWidget(self.le_maxtheta)
        self.le_n0 = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_n0.setObjectName(_fromUtf8("le_n0"))
        self.verticalLayout_5.addWidget(self.le_n0)
        self.le_e0 = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_e0.setObjectName(_fromUtf8("le_e0"))
        self.verticalLayout_5.addWidget(self.le_e0)
        self.le_phie = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_phie.setObjectName(_fromUtf8("le_phie"))
        self.verticalLayout_5.addWidget(self.le_phie)
        self.le_le = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_le.setObjectName(_fromUtf8("le_le"))
        self.verticalLayout_5.addWidget(self.le_le)
        self.le_phi1 = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_phi1.setObjectName(_fromUtf8("le_phi1"))
        self.verticalLayout_5.addWidget(self.le_phi1)
        self.le_nu = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_nu.setObjectName(_fromUtf8("le_nu"))
        self.verticalLayout_5.addWidget(self.le_nu)
        self.le_r = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.le_r.setObjectName(_fromUtf8("le_r"))
        self.verticalLayout_5.addWidget(self.le_r)
        self.label_34 = QtGui.QLabel(self.centralWidget)
        self.label_34.setGeometry(QtCore.QRect(220, 330, 61, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 330, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pb_open_2 = QtGui.QPushButton(self.centralWidget)
        self.pb_open_2.setGeometry(QtCore.QRect(560, 330, 81, 23))
        self.pb_open_2.setObjectName(_fromUtf8("pb_open_2"))
        pkpm.setCentralWidget(self.centralWidget)

        self.retranslateUi(pkpm)
        QtCore.QMetaObject.connectSlotsByName(pkpm)

    def retranslateUi(self, pkpm):
        pkpm.setWindowTitle(QtGui.QApplication.translate("pkpm", "PKPM钢管柱验算", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_open.setText(QtGui.QApplication.translate("pkpm", "打开配筋文件", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("pkpm", "pkpm结果", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("pkpm", "柱编号", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("pkpm", "直径", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("pkpm", "壁厚", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("pkpm", "x轴长度系数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("pkpm", "y轴长度系数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("pkpm", "长度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("pkpm", "抗震等级", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("pkpm", "砼等级", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("pkpm", "钢材", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("pkpm", "弯矩", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("pkpm", "轴力", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("pkpm", "验算过程", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("pkpm", "砼面积", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("pkpm", "钢面积", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("pkpm", "套箍系数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("pkpm", "套箍系数限值", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("pkpm", "N_0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("pkpm", "偏心率", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("pkpm", "考虑偏心率的折减系数phi_e", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("pkpm", "有侧移框架有效长度Le", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("pkpm", "考虑长细比的折减系数phi_1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("pkpm", "N_u", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("pkpm", "回转半径", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("pkpm", "验算结论", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_open_2.setText(QtGui.QApplication.translate("pkpm", "生成计算书", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    pkpm = QtGui.QMainWindow()
    ui = Ui_pkpm()
    ui.setupUi(pkpm)
    pkpm.show()
    sys.exit(app.exec_())

